"""Dynamic, durable child-run contracts and orchestration tools.

This module is deliberately small and provider-neutral.  The parent Agent owns
the task wording; the runtime only validates the safety/effect boundary and
persists the delegation before returning.  There is no in-process child-agent
runner here: child execution is always scheduled by the Durable Runtime.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from typing import Any, Mapping

from .mcp_client import ToolResult
from .run_model import EffectClass, digest_json


@dataclass(frozen=True)
class ChildTaskSpec:
    """A dynamic task generated by the parent Agent for one child Run."""

    node_id: str
    objective: str
    acceptance_criteria: tuple[str, ...] = ()
    description: str = ""
    required: bool = True
    depends_on: tuple[str, ...] = ()
    effect_class: EffectClass = EffectClass.READ_ONLY
    allowed_scope: tuple[str, ...] = ()
    excluded_scope: tuple[str, ...] = ()
    owned_paths: tuple[str, ...] = ()
    context_refs: tuple[str, ...] = ()
    budget: Mapping[str, Any] = field(default_factory=dict)
    timeout_seconds: int = 240
    max_retries: int = 1
    output_schema: Mapping[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        if not self.node_id.strip():
            raise ValueError("child node_id is required")
        if not self.objective.strip():
            raise ValueError("child objective is required")
        if self.required and not self.acceptance_criteria:
            raise ValueError("required child tasks need acceptance_criteria")
        if any(not criterion.strip() for criterion in self.acceptance_criteria):
            raise ValueError("child acceptance_criteria must be non-empty strings")
        if self.timeout_seconds < 1 or self.timeout_seconds > 3600:
            raise ValueError("child timeout_seconds must be in [1, 3600]")
        if self.max_retries < 0 or self.max_retries > 2:
            raise ValueError("child max_retries must be in [0, 2]")
        if self.effect_class not in {
            EffectClass.READ_ONLY,
            EffectClass.WORKSPACE_MUTATION,
        }:
            raise ValueError("child effect_class must be read_only or workspace_mutation")
        if self.effect_class is EffectClass.WORKSPACE_MUTATION and not self.owned_paths:
            raise ValueError("mutating child tasks need owned_paths")
        for field_name, values in (
            ("allowed_scope", self.allowed_scope),
            ("excluded_scope", self.excluded_scope),
            ("owned_paths", self.owned_paths),
            ("context_refs", self.context_refs),
        ):
            if any(not value.strip() for value in values):
                raise ValueError(f"child {field_name} must not contain empty values")

    @classmethod
    def from_dict(cls, raw: Mapping[str, Any], *, index: int = 0) -> "ChildTaskSpec":
        if not isinstance(raw, Mapping):
            raise ValueError(f"sub_specs[{index}] must be an object")
        node_id = str(raw.get("node_id") or raw.get("task_id") or raw.get("id") or "")
        if not node_id:
            node_id = f"child-{index + 1}"
        criteria = raw.get("acceptance_criteria")
        if criteria is None:
            criteria = raw.get("criteria") or ()
        if isinstance(criteria, str):
            criteria = (criteria,)
        effect = raw.get("effect_class", EffectClass.READ_ONLY.value)
        try:
            effect_class = effect if isinstance(effect, EffectClass) else EffectClass(str(effect))
        except ValueError as exc:
            raise ValueError(f"sub_specs[{index}].effect_class is invalid") from exc
        return cls(
            node_id=node_id,
            objective=str(raw.get("objective") or raw.get("title") or ""),
            description=str(raw.get("description") or ""),
            acceptance_criteria=tuple(str(item) for item in criteria or ()),
            required=bool(raw.get("required", True)),
            depends_on=tuple(str(item) for item in raw.get("depends_on") or ()),
            effect_class=effect_class,
            allowed_scope=tuple(str(item) for item in raw.get("allowed_scope") or ()),
            excluded_scope=tuple(str(item) for item in raw.get("excluded_scope") or ()),
            owned_paths=tuple(str(item) for item in raw.get("owned_paths") or ()),
            context_refs=tuple(str(item) for item in raw.get("context_refs") or ()),
            budget=dict(raw.get("budget") or {}),
            timeout_seconds=int(raw.get("timeout_seconds", raw.get("timeout", 240))),
            max_retries=int(raw.get("max_retries", 1)),
            output_schema=dict(raw.get("output_schema") or {}),
        )

    @property
    def digest(self) -> str:
        return digest_json(self.to_dict())

    def to_dict(self) -> dict[str, Any]:
        return {
            "schema_version": "cc-harness.child-task.v1",
            "node_id": self.node_id,
            "objective": self.objective,
            "description": self.description,
            "acceptance_criteria": list(self.acceptance_criteria),
            "required": self.required,
            "depends_on": list(self.depends_on),
            "effect_class": self.effect_class.value,
            "allowed_scope": list(self.allowed_scope),
            "excluded_scope": list(self.excluded_scope),
            "owned_paths": list(self.owned_paths),
            "context_refs": list(self.context_refs),
            "budget": dict(self.budget),
            "timeout_seconds": self.timeout_seconds,
            "max_retries": self.max_retries,
            "output_schema": dict(self.output_schema),
        }


DISPATCH_SUBAGENT_SPEC: dict[str, Any] = {
    "type": "function",
    "function": {
        "name": "dispatch_subagent",
        "description": (
            "Create durable child Runs from the current task context. The task "
            "wording is supplied by the parent; dispatch returns immediately "
            "after durable scheduling and never runs an in-process subagent."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "sub_specs": {
                    "type": "array",
                    "minItems": 1,
                    "maxItems": 10,
                    "items": {
                        "type": "object",
                        "properties": {
                            "node_id": {"type": "string"},
                            "objective": {"type": "string"},
                            "description": {"type": "string"},
                            "acceptance_criteria": {"type": "array", "items": {"type": "string"}},
                            "required": {"type": "boolean", "default": True},
                            "depends_on": {"type": "array", "items": {"type": "string"}},
                            "effect_class": {"type": "string", "enum": ["read_only", "workspace_mutation"]},
                            "allowed_scope": {"type": "array", "items": {"type": "string"}},
                            "excluded_scope": {"type": "array", "items": {"type": "string"}},
                            "owned_paths": {"type": "array", "items": {"type": "string"}},
                            "context_refs": {"type": "array", "items": {"type": "string"}},
                            "budget": {"type": "object"},
                            "timeout_seconds": {"type": "integer", "minimum": 1, "maximum": 3600},
                            "max_retries": {"type": "integer", "minimum": 0, "maximum": 2},
                            "output_schema": {"type": "object"},
                        },
                        "required": ["objective"],
                    },
                },
                "max_fan_out": {"type": "integer", "minimum": 1, "maximum": 10, "default": 3},
            },
            "required": ["sub_specs"],
        },
    },
}


ACCEPT_CHILD_CANDIDATE_SPEC: dict[str, Any] = {
    "type": "function",
    "function": {
        "name": "accept_child_candidate",
        "description": "Integrate a mutating child candidate only after the parent verifies its evidence.",
        "parameters": {
            "type": "object",
            "properties": {"child_run_id": {"type": "string"}},
            "required": ["child_run_id"],
        },
    },
}


REJECT_CHILD_CANDIDATE_SPEC: dict[str, Any] = {
    "type": "function",
    "function": {
        "name": "reject_child_candidate",
        "description": "Reject a mutating child candidate and preserve the reason in the parent Run.",
        "parameters": {
            "type": "object",
            "properties": {"child_run_id": {"type": "string"}, "reason": {"type": "string"}},
            "required": ["child_run_id", "reason"],
        },
    },
}


async def durable_dispatch_subagent_handler(
    args: Mapping[str, Any], *, coordinator, run_id: str, **_: Any
) -> ToolResult:
    try:
        raw_specs = args.get("sub_specs") or ()
        max_fan_out = int(args.get("max_fan_out", 3))
        if not 1 <= max_fan_out <= 10:
            raise ValueError("max_fan_out must be in [1, 10]")
        if not 1 <= len(raw_specs) <= max_fan_out:
            raise ValueError(f"sub_specs length must be in [1, {max_fan_out}]")
        specs = tuple(ChildTaskSpec.from_dict(item, index=index) for index, item in enumerate(raw_specs))
        if len({spec.node_id for spec in specs}) != len(specs):
            raise ValueError("child node_id values must be unique")
        receipts = await coordinator.create_children(run_id, specs)
    except (TypeError, ValueError, KeyError) as exc:
        return ToolResult.error(str(exc), f"[Tool Error] durable child dispatch rejected: {exc}")
    payload = {
        "schema_version": "cc-harness.child-dispatch-result.v1",
        "parent_run_id": run_id,
        "children": [
            {
                "child_run_id": item.child_run_id,
                "node_id": item.node_id,
                "status": "queued",
            }
            for item in receipts
        ],
        "communication": "parent_events_only",
    }
    return ToolResult.success(json.dumps(payload, ensure_ascii=False, sort_keys=True), source="durable_coordinator", capability="child_dispatch")


async def durable_accept_child_candidate_handler(args: Mapping[str, Any], *, coordinator, run_id: str, **_: Any) -> ToolResult:
    child_run_id = str(args.get("child_run_id") or "")
    if not child_run_id:
        return ToolResult.error("child_run_id is required", "[Tool Error] child_run_id is required")
    try:
        result = await coordinator.accept_child_candidate(run_id, child_run_id)
    except (TypeError, ValueError, KeyError) as exc:
        return ToolResult.error(str(exc), f"[Tool Error] candidate acceptance failed: {exc}")
    return ToolResult.success(json.dumps(result, ensure_ascii=False, sort_keys=True), source="durable_coordinator", capability="child_acceptance")


async def durable_reject_child_candidate_handler(args: Mapping[str, Any], *, coordinator, run_id: str, **_: Any) -> ToolResult:
    child_run_id = str(args.get("child_run_id") or "")
    reason = str(args.get("reason") or "")
    if not child_run_id or not reason:
        return ToolResult.error("child_run_id and reason are required", "[Tool Error] child_run_id and reason are required")
    try:
        await coordinator.reject_child_candidate(run_id, child_run_id, reason)
    except (TypeError, ValueError, KeyError) as exc:
        return ToolResult.error(str(exc), f"[Tool Error] candidate rejection failed: {exc}")
    return ToolResult.success(json.dumps({"child_run_id": child_run_id, "status": "rejected"}, sort_keys=True), source="durable_coordinator", capability="child_acceptance")


__all__ = [
    "ACCEPT_CHILD_CANDIDATE_SPEC",
    "ChildTaskSpec",
    "DISPATCH_SUBAGENT_SPEC",
    "REJECT_CHILD_CANDIDATE_SPEC",
    "durable_accept_child_candidate_handler",
    "durable_dispatch_subagent_handler",
    "durable_reject_child_candidate_handler",
]
